ci(test.yaml,update-badges.yaml): retry download-artifact

diff --git a/.github/workflows/update-badges.yaml b/.github/workflows/update-badges.yaml
--- a/.github/workflows/update-badges.yaml
+++ b/.github/workflows/update-badges.yaml
@@ -54,10 +54,27 @@ jobs:
       - name: Checkout Repository
         uses: actions/checkout@v4
 
-      - name: Download Badge Data Artifact
-        uses: actions/download-artifact@v4
-        with:
-          name: badge-data
+      - name: Retry downloading badge data artifact
+        id: download-artifact
+        run: |
+          max_retries=3
+          attempt=0
+          success=false
+          while [ $attempt -lt $max_retries ]; do
+            echo "Attempt $((attempt + 1)) to download artifact"
+            if actions/download-artifact@v4 --name badge-data; then
+              success=true
+              break
+            else
+              attempt=$((attempt + 1))
+              echo "Download failed. Retrying..."
+              sleep 10
+            fi
+          done
+          if [ "$success" = false ]; then
+            echo "Failed to download artifact after $max_retries attempts. Exiting."
+            exit 1
+          fi
 
       - name: "Load Badge Data"
         run: |
